# -*- coding: utf-8 -*-
"""TITANIC SURVIVORS

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_MwiW6JEkbv5-sf_9379OkIBt38CqhXK

# **TITANIC SURVIVORS ANALYSIS**
"""

import pandas as pd
import numpy as np

"""now i am importing the csv file so as to take the values.i have read the file and then chose to dataframe it."""

df = pd.DataFrame(pd.read_csv('/train (1).csv'))
df.head()

"""now i want to know the structure of my dataset.so they are:

1.   no of rows*no. of columns
2.   no. of null values




"""

df.shape

df.isnull().sum()

"""now this is a significant missing values.so to take all that out of the dataset so i have the appropriate dataset to analyse,i will remove the values which has more than 35% missing vales."""

drop_col=df.isnull().sum()[df.isnull().sum()>(35/100*df.shape[0])]
drop_col

drop_col.index

df.drop(drop_col.index,axis=1,inplace=True)
df.isnull().sum()

"""not all column could be drop because they consist of less missing vaue,they contain data which is helpful for analysis while cabin had more than 35% of missing values and therefore wasnt useful for us.

now from the above output we saw we still have two areas where we have null values.we will fill that data with a specific value.
"""

df.fillna(df.mean(),inplace=True)
df.isnull().sum()

"""now the age column has no missing values s we have filled it with mean.but embarked column still has missing value because it consist of string and we can't have the mean of the string. """

df['Embarked'].describe()

df['Embarked'].fillna('S',inplace=True)

df.isnull().sum()

df.corr()

"""by this we can derive the relation between the fare and the passenger class.
**higher the passenger class,higher the fare.**
"""

df['FamilySize']=df['SibSp']+df['Parch']
df.drop(['SibSp','Parch'],axis=1,inplace=True)
df.corr()

"""by this we can conclude that: 



* **survival rate was higher for higher class.**
*   **family size has no relation with the survival rate**


"""

df['Alone']=[0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean()

"""by this we can conclude that if the person was alone he or she had less chance of living as there are chances that the person who was travelling with his family might have been rich and prioritized over other."""

df[['Alone','Fare']].corr()

df.groupby(['Embarked'])['Survived'].mean()